name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create zip
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'yop.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: Upload zip
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "yop.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
